### ISSUE TITLE
Permacast V3 Master Contract

### ISSUE THREAD

**Issue by charmful0x** [Parallel-news/permacast#46]
## About
This issue is about the new features, limits, and functionalities introduced in the third version of Permacast's Master contract.

## New limits

These are the new limits (mostly string length extreme) 
### Podcast Metadata
| metadata  | min length |  max length | notes/fixes |
| ------------- | ------------- | ------------- |  ------------- |  
| podcast name      | 2     | 500 | added flexibility ~ 77 - 100 words|
| podcast description     | 10    | 15000 | added flexibility ~ 2308 - 3000 words |
| email    | 0    | 320 | none |
| author name | 2 | 150| added flexibility |
| categories | 1 | 300 | added support for length equal to 1 (e.g. in Chinese) |
| language code | 2 | 2| none |

### Episode Metadata
| metadata  | min length |  max length | notes/fixes |
| ------------- | ------------- | ------------- |  ------------- |  
| episode name      | 3     | 500 | added flexibility ~ 77 - 100 words |
| episode description     | 1    | 5000 | added flexibility ~ 769 - 1000 words |

### Reduce the signatures required to edit a podcast/episode
All of the podcast/episode object's metadata (name, description, etc.) can be updated by invoking a single function `updatePodcastMetadata` and `updateEpisodeMetadata`.

### Factory Super Admins
The Factory Super Admins have the permission to create a podcast or an episode and update their metadata. They are added as super admins via the contract owner, and they can remove themselves from this position or be removed by the contract owner.

### Podcasts Maintainers
Podcast Maintainers have a lower set of permissions, they can only upload episodes and edit them. Maintainers are added and removed by the contract owner.

### Reduce non-necessary required inputs to invoke with some functions
The confusing `id` & `index` don't longer exist, To update a podcast only the `pid` is required, and to add/update an episode, only the `eid` is required.

### Auto-protection from duplicated uploads
When the `caller` sends more than a transaction to create a podcast (or an episode) with the same `name` property within 5 blocks, only one transaction (first one that get mined) will pass through. Thus, it reduces the double uploads mistake.

### Configurable RSS metadata
Podcast's metadata used to generated RSS feeds are now mutable

## Note
The limits and features listed previously are "init", and can be changed according to the future issue's discussion.

**Comment by SiyuSiyuYang** [comment]
1. 5000 might still be tight for `podcast description` - adding reference links or using bilingual really expands the shownote length; I looked into our past shownotes, and longer shownotes can go up to 15k characters, which might be a blocker if somebody wants to sync their existing RSS to permacast.
2. What is the difference between super admin and podcast maintainers?

**Comment by charmful0x** [comment]
Hello @SiyuSiyuYang and thanks for the feedback!

1- That's not a problem, we will adjust the max-limit
2- super admins are 1 level below the contract owner, they can create episodes and upload episodes (and edit them). While the maintainers can only edit and upload episodes (they cannot create podcasts). This method facilitates a secure and decentralized solution for podcasting moderation.

**Comment by SiyuSiyuYang** [comment]
@charmful0x Thanks for the clarification - makes a ton of sense :) Looking forward to the update!!

**Comment by xylophonez** [comment]
According to Apple, they impose the following:

* Title (episode and/or show): 255 char
* Desc (episode and/or show): 4,000 char

If we can stick to this, I think we're all fine. 

@charmful0x your point about passing this off to a txid is great and sounds necessary. However, since (i think) 2048 bytes is 2048 char, can we not allow some version of:

2048 - episode.title?

Either way, let's go with this model!

**Comment by charmful0x** [comment]
thanks, @xylophonez !!

The [commit above](https://github.com/Parallel-news/permacast/commit/af2bcb85e4163cb750f03f9ce0965cd5763f6a92) introduces this feature and bypasses the Arweave network tagging bytes size limitation.

But instead of passing the episode/podcast description as a separated data TX, it should be seeded with the contract's interaction transaction, which reduces the required signatures (hence TXs) to interact with the smart contract.

This feature can also be used with the podcast/episode name (aka title) handling. WDYT?

**Comment by charmful0x** [comment]
# Factories Oracle - Proposal

## About
The Factories Oracle is smartweave contract operated by the Permacast team.  The purpose of this contract is to serve as an oracle of metadata limitations for the deployed factories. 

A factory owner has the freedom of choice to make his factory up-to-date with the Factories Oracle contract whenever he decides to.

## Technical Logic Flow

### Oracle's feed
The feed of metadata that can be read via the Factories Oracle consists of:
- podcast's name length limits
- podcast's description length limits
- podcast's author name length limits
- episode's name length limits
- episode's description length limits
- language's char code type (currently ISO 639-1:2002)

### Reading the oracle and updating a factory

#### V3 state contract required changes:
Make the metadata limitations dynamic by declaring it in the factory's state instead of having it hardcoded in the factory's source code:

```json
{
  "podcasts": [],
  "superAdmins": [],
  "maintainers": [],
  "v2SourceCode": "KrMNSCljeT0sox8bengHf0Z8dxyE0vCTLEAOtkdrfjM",
  "hasMigrated": false,
  "ownerSwapped": false,
  // requested stated modification 
  "limitations": { 
    "episode_name": {
      "min": 3,
      "max": 500
    },
    "podcast_name": {
      "min": 2,
      "max": 500
    }
     ...etc
  }
}
```

#### V3 contract source code required changes:
To make this possible, a new function `fetchOracle` is required to update the `limitations` in a V3 factory state. Invoking this new function is permissioned and requires `superAdmins` privileges.

```js
if (input.function === "fetchOracle") {
  /**
   * @dev read the oracle's state and update
   * the limitations object of the factory (contract's state)
   *
   * @return state
   *
   **/
  await _isSuperAdmin(true, caller);

  const OracleAddress = "...TBD...";
  const oracleState = await SmartWeave.contracts.readContractState(
    OracleAddress
  );

  // overwrite the factory's limitations object
  state.limitations = oracleState.limitations;

  return { state };
}
```

## Benefits
This feature makes the deployed factories dynamic with any possible new factories release (Master Contract new source code release) that depends on the factory's metadata limitations.

**Comment by charmful0x** [comment]
# Video Podcasts - Proposal

## About
Add support for uploading video episodes instead of audio episodes only.

## Technical Logic Flow
When a factory's owner (or super admin) decides to create a new podcast object, they can decide on the MIME type episodes to support in this podcast object: `video` or `audio`.

### V3 source code change

#### 1- function: `createPodcast`
```js
const contentType = input.contentType === "video" ? "video/*" : "audio/*";

podcasts.push({
  pid: pid,
  contentType: contentType,
  createdAtBlockheight: SmartWeave.block.height, // blockheight - V3 metadata
  createdAt: SmartWeave.block.timestamp, // block's timestamp
  index: _getPodcastIndex(), // id equals the index of the podacast obj in the podcasts array
  childOf: SmartWeave.contract.id,
  owner: caller,
  podcastName: name,
  author: author,
  email: email,
  description: desc,
  language: lang,
  explicit: isExplicit,
  categories: categories.split(",").map((category) => category.trim()),
  cover: cover,
  isVisible: true,
  episodes: [],
  logs: [pid],
});
```

#### 2- function: `addEpisode`
The `ContentType` defined in the podcast object will be bound to this podcast and only data TXs of the bound MIME type will be accepted in the episode adding interaction.

```js
...
const input = input.pid;
const pidIndex = _getAndValidatePidIndex(pid);
const contentType = state.podcasts[pidIndex]["contentType"];
const TxMetadata = await _validateDataTransaction(input.episodeTx, contentType);
...
```

## Benefits
Allow flexible content creation (podcasts) over Permacast and facilitate web2 backward compatibility and allow various importing tools.
