### ISSUE TITLE
Add a badge to the nav bar showing the user's ANS name and profile picture

### ISSUE THREAD

**Issue by xylophonez** [Parallel-news/permacast#52]
Expanding on #50, which added support for ANS domains to be shown **on the disconnect button** in the nav bar, I propose we add a new design pattern similar to Uniswap's nav bar, which displays the address and an icon in a separate element. We can then release this component as a lib, to make it easy for other apps to do the same.

![Screenshot (19)](https://user-images.githubusercontent.com/69069725/167370146-6d78d82b-d4a1-4fd2-aea3-9d737800f886.png)

**Comment by charmful0x** [comment]
merged successfully in #53
